# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: communication/proto/tensor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'communication/proto/tensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n communication/proto/tensor.proto\x12\x06legion\"\xe1\x01\n\x0bTensorProto\x12\r\n\x05shape\x18\x01 \x03(\x03\x12(\n\x05\x64type\x18\x02 \x01(\x0e\x32\x19.legion.TensorProto.DType\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12,\n\x0b\x63ompression\x18\x04 \x01(\x0b\x32\x17.legion.CompressionInfo\x12\x0c\n\x04name\x18\x05 \x01(\t\"O\n\x05\x44Type\x12\x0b\n\x07\x46LOAT32\x10\x00\x12\x0b\n\x07\x46LOAT16\x10\x01\x12\x0c\n\x08\x42\x46LOAT16\x10\x02\x12\x08\n\x04INT8\x10\x03\x12\t\n\x05INT32\x10\x04\x12\t\n\x05INT64\x10\x05\"\x9f\x02\n\x0f\x43ompressionInfo\x12\x35\n\x04type\x18\x01 \x01(\x0e\x32\'.legion.CompressionInfo.CompressionType\x12\r\n\x05scale\x18\x02 \x01(\x02\x12\x12\n\nzero_point\x18\x03 \x01(\x02\x12\t\n\x01k\x18\x04 \x01(\x03\x12\x0f\n\x07indices\x18\x05 \x03(\x03\x12\x16\n\x0eoriginal_shape\x18\x06 \x03(\x03\x12\x31\n\x0eoriginal_dtype\x18\x07 \x01(\x0e\x32\x19.legion.TensorProto.DType\"K\n\x0f\x43ompressionType\x12\x08\n\x04NONE\x10\x00\x12\x11\n\rINT8_QUANTIZE\x10\x01\x12\x0f\n\x0bTOPK_SPARSE\x10\x02\x12\n\n\x06ONEBIT\x10\x03\"\xb8\x01\n\x0bTensorChunk\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\x03\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12(\n\x05\x64type\x18\x04 \x01(\x0e\x32\x19.legion.TensorProto.DType\x12\r\n\x05shape\x18\x05 \x03(\x03\x12,\n\x0b\x63ompression\x18\x06 \x01(\x0b\x32\x17.legion.CompressionInfo\x12\x0c\n\x04name\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'communication.proto.tensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORPROTO']._serialized_start=45
  _globals['_TENSORPROTO']._serialized_end=270
  _globals['_TENSORPROTO_DTYPE']._serialized_start=191
  _globals['_TENSORPROTO_DTYPE']._serialized_end=270
  _globals['_COMPRESSIONINFO']._serialized_start=273
  _globals['_COMPRESSIONINFO']._serialized_end=560
  _globals['_COMPRESSIONINFO_COMPRESSIONTYPE']._serialized_start=485
  _globals['_COMPRESSIONINFO_COMPRESSIONTYPE']._serialized_end=560
  _globals['_TENSORCHUNK']._serialized_start=563
  _globals['_TENSORCHUNK']._serialized_end=747
# @@protoc_insertion_point(module_scope)
