# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from communication.proto import tensor_pb2 as communication_dot_proto_dot_tensor__pb2
from communication.proto import worker_pb2 as communication_dot_proto_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in communication/proto/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerServiceStub(object):
    """Worker service for peer-to-peer communication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetParameters = channel.unary_unary(
                '/legion.WorkerService/GetParameters',
                request_serializer=communication_dot_proto_dot_worker__pb2.ParameterRequest.SerializeToString,
                response_deserializer=communication_dot_proto_dot_worker__pb2.ParameterResponse.FromString,
                _registered_method=True)
        self.StreamParameters = channel.unary_stream(
                '/legion.WorkerService/StreamParameters',
                request_serializer=communication_dot_proto_dot_worker__pb2.ParameterRequest.SerializeToString,
                response_deserializer=communication_dot_proto_dot_tensor__pb2.TensorChunk.FromString,
                _registered_method=True)
        self.SendGradients = channel.unary_unary(
                '/legion.WorkerService/SendGradients',
                request_serializer=communication_dot_proto_dot_worker__pb2.GradientUpdate.SerializeToString,
                response_deserializer=communication_dot_proto_dot_worker__pb2.GradientAck.FromString,
                _registered_method=True)
        self.AllGather = channel.unary_unary(
                '/legion.WorkerService/AllGather',
                request_serializer=communication_dot_proto_dot_worker__pb2.AllGatherRequest.SerializeToString,
                response_deserializer=communication_dot_proto_dot_worker__pb2.AllGatherResponse.FromString,
                _registered_method=True)
        self.ReduceScatter = channel.unary_unary(
                '/legion.WorkerService/ReduceScatter',
                request_serializer=communication_dot_proto_dot_worker__pb2.ReduceScatterRequest.SerializeToString,
                response_deserializer=communication_dot_proto_dot_worker__pb2.ReduceScatterResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/legion.WorkerService/Ping',
                request_serializer=communication_dot_proto_dot_worker__pb2.PingRequest.SerializeToString,
                response_deserializer=communication_dot_proto_dot_worker__pb2.PingResponse.FromString,
                _registered_method=True)


class WorkerServiceServicer(object):
    """Worker service for peer-to-peer communication
    """

    def GetParameters(self, request, context):
        """Request a parameter shard from another worker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamParameters(self, request, context):
        """Stream large parameters in chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendGradients(self, request, context):
        """Send gradient updates to parameter owner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllGather(self, request, context):
        """Participate in all-gather collective
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReduceScatter(self, request, context):
        """Participate in reduce-scatter collective
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Ping for latency measurement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetParameters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParameters,
                    request_deserializer=communication_dot_proto_dot_worker__pb2.ParameterRequest.FromString,
                    response_serializer=communication_dot_proto_dot_worker__pb2.ParameterResponse.SerializeToString,
            ),
            'StreamParameters': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamParameters,
                    request_deserializer=communication_dot_proto_dot_worker__pb2.ParameterRequest.FromString,
                    response_serializer=communication_dot_proto_dot_tensor__pb2.TensorChunk.SerializeToString,
            ),
            'SendGradients': grpc.unary_unary_rpc_method_handler(
                    servicer.SendGradients,
                    request_deserializer=communication_dot_proto_dot_worker__pb2.GradientUpdate.FromString,
                    response_serializer=communication_dot_proto_dot_worker__pb2.GradientAck.SerializeToString,
            ),
            'AllGather': grpc.unary_unary_rpc_method_handler(
                    servicer.AllGather,
                    request_deserializer=communication_dot_proto_dot_worker__pb2.AllGatherRequest.FromString,
                    response_serializer=communication_dot_proto_dot_worker__pb2.AllGatherResponse.SerializeToString,
            ),
            'ReduceScatter': grpc.unary_unary_rpc_method_handler(
                    servicer.ReduceScatter,
                    request_deserializer=communication_dot_proto_dot_worker__pb2.ReduceScatterRequest.FromString,
                    response_serializer=communication_dot_proto_dot_worker__pb2.ReduceScatterResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=communication_dot_proto_dot_worker__pb2.PingRequest.FromString,
                    response_serializer=communication_dot_proto_dot_worker__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'legion.WorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('legion.WorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerService(object):
    """Worker service for peer-to-peer communication
    """

    @staticmethod
    def GetParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legion.WorkerService/GetParameters',
            communication_dot_proto_dot_worker__pb2.ParameterRequest.SerializeToString,
            communication_dot_proto_dot_worker__pb2.ParameterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamParameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/legion.WorkerService/StreamParameters',
            communication_dot_proto_dot_worker__pb2.ParameterRequest.SerializeToString,
            communication_dot_proto_dot_tensor__pb2.TensorChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendGradients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legion.WorkerService/SendGradients',
            communication_dot_proto_dot_worker__pb2.GradientUpdate.SerializeToString,
            communication_dot_proto_dot_worker__pb2.GradientAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllGather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legion.WorkerService/AllGather',
            communication_dot_proto_dot_worker__pb2.AllGatherRequest.SerializeToString,
            communication_dot_proto_dot_worker__pb2.AllGatherResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReduceScatter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legion.WorkerService/ReduceScatter',
            communication_dot_proto_dot_worker__pb2.ReduceScatterRequest.SerializeToString,
            communication_dot_proto_dot_worker__pb2.ReduceScatterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/legion.WorkerService/Ping',
            communication_dot_proto_dot_worker__pb2.PingRequest.SerializeToString,
            communication_dot_proto_dot_worker__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
